services:
  - type: web
    name: my-elysia-app
    env: docker
    plan: free
    buildCommand: bun install
    startCommand: bun run start
    region: oregon
    envVars:
      - key: BUN_VERSION
        value: "latest"
